services:
  - type: web
    name: django-app
    env: python
    plan: free 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: spotx-portfolio.onrender.com
